// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woywfcpcbqgeeqcinwoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveXdmY3BjYnFnZWVxY2lud296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDUwNDUsImV4cCI6MjA3MzYyMTA0NX0.9f-HUst5HA4KYnkt2CqsLaylXQN1DBf_J9gXNtms3Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});